# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PAR-Repository-Query
version:      0.12
version_from: lib/PAR/Repository/Query.pm
installdirs:  site
requires:
    version:                       0.50

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
